# Вероятность и моменты

Вероятностная модель задаёт язык, на котором позже формулируются likelihood,
fit-процедуры и статистические выводы. Поэтому первая глава должна зафиксировать
не только определения, но и рабочие вычислительные объекты.

## Случайные величины и ожидание

Пусть случайная величина $X$ имеет плотность $f(x)$ или функцию вероятностей в
дискретном случае. Математическое ожидание играет роль базового усреднения:

$$
\E[X] = \int x f(x)\,\dd x
$$

или, в дискретной постановке,

$$
\E[X] = \sum_x x\,\mathbb{P}(X=x).
$$

## Начальные и центральные моменты

Начальный момент порядка $k$ определяется как

$$
\mu_k' = \E[X^k].
$$

Центральный момент порядка $k$ определяется как

$$
\mu_k = \E[(X-\E[X])^k].
$$

В частности,

$$
\mu_1' = \E[X],
\qquad
\mu_2 = \Var(X).
$$

## Выборочные оценки

Для выборки $x_1,\dots,x_n$ естественной оценкой начального момента служит

$$
m_k' = \frac{1}{n}\sum_{i=1}^{n} x_i^k,
$$

а соответствующий выборочный центральный момент можно записать как

$$
m_k = \frac{1}{n}\sum_{i=1}^{n}(x_i-\bar{x})^k,
\qquad
\bar{x} = \frac{1}{n}\sum_{i=1}^{n} x_i.
$$

Для дисперсии часто используют несмещённую оценку

$$
s^2 = \frac{1}{n-1}\sum_{i=1}^{n}(x_i-\bar{x})^2.
$$

Эта техника понадобится дальше постоянно: в toy MC, в диагностике fit'ов и в
анализе устойчивости оценок. Базовое систематическое изложение можно держать в
голове по [@cowan1998].

::: {.notebook-card}
### Companion notebook

К этой главе подключён небольшой ноутбук с вычислением выборочных моментов и
простым графиком для игрушечной выборки.

<div class="notebook-actions">
  <a class="notebook-link notebook-link-primary" href="../notebooks/probability_demo.qmd">Открыть ноутбук</a>
</div>
:::
